### ISSUE TITLE
Possible to use the VirusTotal API to check files after user upload?

### ISSUE THREAD

**Issue by privacytoolsIO** [timvisee/send-instances#17]
Hi guys, first of all great job and thanks for bringing Send back to life. I've recently included it in our list of [File Sharing and Synchronizating](https://www.privacytools.io/#files). I'm not a developer, but I'm curious to find out if it would be possible, viable and realistic to include the VirusTotal API after users upload files to an instance:

https://developers.virustotal.com/reference/overview

This would fight the malware problem. Since the free API is limited, it's worth considering to include a simple premium model in Send in order for hosters to pay for the API etc.

Please let me know what you think.
BurungHantu

**Comment by timvisee** [comment]
If this would be used on upload, checking must be done on the client. This can be bypassed by a malicious.

Nor do I like to integrate other services into a system on which sensitive files are shared, whatever the integration provides. The same goes for providing a premium model, or for example, a link shortener.

**Comment by privacytoolsIO** [comment]
That makes sense. Thanks for your kind reply, tim.
