### ISSUE TITLE
The instance https://files.psu.ru doesn't accept any password

### ISSUE THREAD

**Issue by YorkZ** [timvisee/send-instances#20]
For any files I uploaded to this site, if I protected it with a password at the time of uploading, the file will be reject for downloading with an `Incorrect password` error. Files uploaded without password protection worked fine though.

**Comment by timvisee** [comment]
I just confirmed this is the case, thanks for noticing.

**Comment by YorkZ** [comment]
Thanks, but what can be done on this? Will the owner of the site know the issue and maybe address it?

**Comment by YorkZ** [comment]
So how to report the issue to the owner?

**Comment by YorkZ** [comment]
Who add his site to this list?

**Comment by timvisee** [comment]
I did, as I came across it on the internet.

See 44cfc75314a16977a565a61b3cbd41f786f0d438

**Comment by YorkZ** [comment]
Thanks. Just curious how you knew that site.

**Comment by timvisee** [comment]
Based on a quick search it seems to belong to Perm State University: https://duckduckgo.com/?q=site%3Apsu.ru
