### ISSUE TITLE
New instance: SeineTransfert [10Gb]

### ISSUE THREAD

**Issue by ReveltyOnGit** [timvisee/send-instances#26]
Hello,
This is my Send Instance : https://transferer.seinetransfert.fr/ (DNS resolution may take down the website).
Thanks.

**Comment by timvisee** [comment]
Thanks!

> (DNS resolution may take down the website)

What do you mean with this?

**Comment by ReveltyOnGit** [comment]
The domain name is new which may make the site unavailable to some people at this time.

**Comment by timvisee** [comment]
It is reachable for me right now.

Added!
