### ISSUE TITLE
Unlisted public instance: https://send.neoway.com.br/

### ISSUE THREAD

**Issue by colans** [timvisee/send-instances#3]
https://send.neoway.com.br/ doesn't appear to be listed here.  It was mentioned at https://support.mozilla.org/en-US/questions/1329309.

It has the Mozilla branding though so maybe not.  Are we listing those as well?

**Comment by timvisee** [comment]
Added. Thanks!

> It has the Mozilla branding though so maybe not. Are we listing those as well?

Yes, that is fine.
