### ISSUE TITLE
suggestion for new instance: Internxt Send

### ISSUE THREAD

**Issue by Simplenuity** [timvisee/send-instances#53]
Would Internxt Send be a good candidate for the list of instances? It offers E2EE.

**Instance URL**
https://send.internxt.com

**Size limit**
5GiB

**Time limit**
15 days

**DL limit**
n/a

**Links/Notes**
https://github.com/internxt
https://help.internxt.com/

**Country**
Spain (company)
All encrypted user data is stored within the European Union: France, Germany and Poland.

Thanks for your consideration

PS: I have no affiliations

**Comment by tdulcet** [comment]
Thanks for the information. Unfortunately, this list is only for (Firefox) Send instances that support the same API for uploading and downloading files.
