### ISSUE TITLE
details send.aslaets.be

### ISSUE THREAD

**Issue by alexslaets** [timvisee/send-instances#56]
Sorry for not opening a pull request.  
The instance is located in belgium not in germany.
Contact is mailto:webmaster@aslaets.be

**Comment by tdulcet** [comment]
OK, thanks for the information. I checked a couple of IP geolocation databases and they both said the instance was in Germany:
![image](https://github.com/timvisee/send-instances/assets/15305150/d634bfe8-e82a-4d87-8c02-b9dd9ba1dad7)
Anyway, please feel free to create a new PR to fix it or I can do so tomorrow.
