### ISSUE TITLE
Remove dead instance send.zcyph.cc?

### ISSUE THREAD

**Issue by BitesizedLion** [timvisee/send-instances#77]
send.zcyph.cc has been down for over 2 months now, safe to consider it dead?

**Comment by tdulcet** [comment]
We typically wait at least 90 days, as instances have come back before, but feel free to create an early pull request to remove it.

**Comment by timvisee** [comment]
I think it's fine to remove them a bit earlier. If it's offline for such periods it already proves to be unreliable, so I'm not sure we want to keep it on the list even if it comes back online.

Thanks for noting this!

**Comment by timvisee** [comment]
Removed in <https://github.com/timvisee/send-instances/commit/32980c21f9359d37c89edaaeea4e945f59759e0d>
